name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:	
    runs-on: ubuntu-latest	

    steps:	
    - uses: actions/checkout@v2	

    - name: Login to Docker Hub	
      run: docker login -u phillaf -p ${{ secrets.DOCKERHUB_PASS }}	

    - name: Build Docker image	
      run: docker build -t phillaf/phphil:latest .

    - name: Publish Docker image	
      run: docker push phillaf/phphil
